<a href="https://colab.research.google.com/github/vyshnavi-2/2303A51617-Batch-07/blob/main/Lab_2_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*2303A51617*
Batch-07
Lab-02


**1.Student Grades Analysis Using NumPy Arrays**

In [1]:
import numpy as np

In [3]:
marks=np.array([[70,95,99],[93,85,76],[67,91,55]])

print(np.mean(marks))
print("The average marks of students:",np.mean(marks))
print(np.min(marks))
print("The minimum marks of students:",np.min(marks))
print(np.max(marks))
print("The maximum marks of students:",np.max(marks))

81.22222222222223
The average marks of students: 81.22222222222223
55
The minimum marks of students: 55
99
The maximum marks of students: 99


In [4]:
#Use slicing to retrieve marks of specific students
print(marks[2])

[67 91 55]


In [5]:
#Use boolean indexing to find students scoring above 80
above_80=marks>80
print("marks above 80:",above_80)

marks above 80: [[False  True  True]
 [ True  True False]
 [False  True False]]


In [6]:
#Reshape the array to observe subject-wise performance
reshaped_arr=marks.T
print("Subject wise performance:",reshaped_arr)


Subject wise performance: [[70 93 67]
 [95 85 91]
 [99 76 55]]


**2.Employee Salary Analysis with pandas DataFrame**

In [7]:
import pandas as pd

In [8]:
data={
    'EmployeeName':['John','Jane','Mike','Emily','David'],
    'EmployeeID':[101,102,103,104,105],
    'Department':['HR','IT','Finance','HR','IT'],
    'Salary':[60000,75000,55000,62000,70000]
}

In [9]:
#Filter employees with salary > 50,000
df=pd.DataFrame(data)
filtered_df=df[df['Salary']>50000]
print(filtered_df)

  EmployeeName  EmployeeID Department  Salary
0         John         101         HR   60000
1         Jane         102         IT   75000
2         Mike         103    Finance   55000
3        Emily         104         HR   62000
4        David         105         IT   70000


In [10]:
#Sort the DataFrame by salary in descending order
sorted_df=df.sort_values(by='Salary',ascending=False)
print(sorted_df)

  EmployeeName  EmployeeID Department  Salary
1         Jane         102         IT   75000
4        David         105         IT   70000
3        Emily         104         HR   62000
0         John         101         HR   60000
2         Mike         103    Finance   55000


In [11]:
#Add a new column for Bonus (10% of salary)
df['Bonus']=0.1*df['Salary']
print(df)

  EmployeeName  EmployeeID Department  Salary   Bonus
0         John         101         HR   60000  6000.0
1         Jane         102         IT   75000  7500.0
2         Mike         103    Finance   55000  5500.0
3        Emily         104         HR   62000  6200.0
4        David         105         IT   70000  7000.0


In [12]:
#Calculate total salary expense including bonuses
total_expense=df['Salary'].sum()+df['Bonus'].sum()
print("Total salary expense including bonuses:",total_expense)

Total salary expense including bonuses: 354200.0


In [13]:
#Save the DataFrame to a CSV file
df.to_csv('employee_data.csv',index=False)
print("Saved to employee_salary_with_bonus.csv")

Saved to employee_salary_with_bonus.csv
